"""Port of src/constants.ts"""

SHEKEL_CURRENCY_SYMBOL = "\u20aa"
SHEKEL_CURRENCY_KEYWORD = '\u05e9"\u05d7'
ALT_SHEKEL_CURRENCY = "NIS"
SHEKEL_CURRENCY = "ILS"

DOLLAR_CURRENCY_SYMBOL = "$"
DOLLAR_CURRENCY = "USD"

EURO_CURRENCY_SYMBOL = "\u20ac"
EURO_CURRENCY = "EUR"

ISO_DATE_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
